-- MySQL Script generated by MySQL Workbench
-- Tue Feb 25 13:31:28 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`contact_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`contact_info` (
  `id_contact` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `street` VARCHAR(100) NULL DEFAULT NULL,
  `number` INT NULL DEFAULT NULL,
  `floor` VARCHAR(10) NULL DEFAULT NULL,
  `door` VARCHAR(10) NULL DEFAULT NULL,
  `city` VARCHAR(100) NULL DEFAULT NULL,
  `postal_code` VARCHAR(10) NULL DEFAULT NULL,
  `country` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_contact`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '	';


-- -----------------------------------------------------
-- Table `optica`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`supplier` (
  `id_supplier` INT NOT NULL AUTO_INCREMENT,
  `fk_supplier_contact_id` INT NOT NULL,
  `fax` VARCHAR(15) NULL DEFAULT NULL,
  `nif` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id_supplier`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE,
  INDEX `contact_id_idx` (`fk_supplier_contact_id` ASC) VISIBLE,
  CONSTRAINT `fk_supplier_contact_id`
    FOREIGN KEY (`fk_supplier_contact_id`)
    REFERENCES `optica`.`contact_info` (`id_contact`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `optica`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`brand` (
  `id_brand` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `supplier_id` INT NOT NULL,
  PRIMARY KEY (`id_brand`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `supplier_id_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `supplier_id`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `optica`.`supplier` (`id_supplier`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `optica`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`customer` (
  `id_customer` INT NOT NULL AUTO_INCREMENT,
  `contact_id` INT NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `registration_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_customer`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `contact_id_idx` (`contact_id` ASC) VISIBLE,
  CONSTRAINT `contact_id`
    FOREIGN KEY (`contact_id`)
    REFERENCES `optica`.`contact_info` (`id_contact`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `optica`.`customer_recommendation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`customer_recommendation` (
  `id_recommendation` INT NOT NULL AUTO_INCREMENT,
  `recommending_customer` INT NOT NULL,
  `recommended_customer` INT NOT NULL,
  `recommendation_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_recommendation`),
  UNIQUE INDEX `unique_recommendation` (`recommending_customer` ASC, `recommended_customer` ASC) VISIBLE,
  INDEX `fk_recommended_customer` (`recommended_customer` ASC) VISIBLE,
  CONSTRAINT `fk_recommended_customer`
    FOREIGN KEY (`recommended_customer`)
    REFERENCES `optica`.`customer` (`id_customer`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recommending_customer`
    FOREIGN KEY (`recommending_customer`)
    REFERENCES `optica`.`customer` (`id_customer`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `optica`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`employee` (
  `id_employee` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_employee`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `optica`.`glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`glasses` (
  `id_glasses` INT NOT NULL AUTO_INCREMENT,
  `brand_id` INT NOT NULL,
  `left_lens_prescription` DECIMAL(5,2) NOT NULL,
  `right_lens_prescription` DECIMAL(5,2) NOT NULL,
  `frame_type` ENUM('floating', 'plastic', 'metal') NOT NULL,
  `frame_color` VARCHAR(45) NOT NULL,
  `left_lens_color` VARCHAR(45) NOT NULL,
  `right_lens_color` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_glasses`),
  INDEX `brand_id_idx` (`brand_id` ASC) VISIBLE,
  CONSTRAINT `brand_id`
    FOREIGN KEY (`brand_id`)
    REFERENCES `optica`.`brand` (`id_brand`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `optica`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`sale` (
  `id_sale` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `glasses_id` INT NOT NULL,
  `sale_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_sale`),
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  INDEX `employee_id_idx` (`employee_id` ASC) VISIBLE,
  INDEX `glasses_id_idx` (`glasses_id` ASC) VISIBLE,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `optica`.`customer` (`id_customer`),
  CONSTRAINT `employee_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `optica`.`employee` (`id_employee`),
  CONSTRAINT `glasses_id`
    FOREIGN KEY (`glasses_id`)
    REFERENCES `optica`.`glasses` (`id_glasses`))
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
